module.exports = async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  let body = req.body;
  if (typeof body === 'string') {
    try { body = JSON.parse(body); } catch (e) {}
  }
  
  const symptom = body?.symptom;
  const device = body?.device || "a computer or electronic device";
  if (!symptom) {
    return res.status(400).json({ error: 'Symptom is required' });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: 'API key is not configured.' });
  }

  const prompt = `You are a professional IT repair technician. A customer reports the following issue for their ${device}: '${symptom}'. First, provide a bolded **Case Summary** (1 brief sentence summarizing their reported problem). Then, provide a brief, 3-step troubleshooting diagnosis specific to this device. Keep the entire response under 75 words and format it clearly.`;

  const postData = JSON.stringify({
    contents: [{ parts: [{ text: prompt }] }]
  });

  const makeRequest = async () => {
    // Switch to gemini-3.5-flash-lite to bypass 503 high demand issues
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent?key=${apiKey}`;

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: postData
    });

    const data = await response.json();

    if (!response.ok) {
      throw { status: response.status, data: data.error?.message || JSON.stringify(data) };
    }

    if (!data.candidates || data.candidates.length === 0) {
      let reason = "Unknown reason.";
      if (data.promptFeedback && data.promptFeedback.blockReason) {
        reason = "Safety Block: " + data.promptFeedback.blockReason;
      }
      throw { status: 500, data: 'No response generated by AI. ' + reason };
    }

    const aiText = data.candidates[0]?.content?.parts?.[0]?.text;
    if (!aiText) {
      throw { status: 500, data: 'AI returned an empty response.' };
    }

    return aiText;
  };

  const delay = (ms) => new Promise(res => setTimeout(res, ms));

  let attempt = 0;
  while (attempt < 3) {
    try {
      const result = await makeRequest();
      return res.status(200).json({ diagnosis: result });
    } catch (error) {
      attempt++;
      
      // Do not retry client errors EXCEPT 408 (Timeout). 429 means we are rate limited or out of quota, so fail fast.
      if (error.status && error.status >= 400 && error.status < 500 && error.status !== 408) {
        return res.status(500).json({ 
          error: `Google API Error (${error.status}): ` + (error.data || "Unknown Error")
        });
      }

      if (attempt >= 3) {
        return res.status(500).json({ 
          error: error.data || 'AI server is currently overloaded. Please try again.'
        });
      }
      
      await delay(500); // Wait 500ms before retry
    }
  }
};
